name: test

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get result
        id: compareresult
        run: echo "::set-output result='true'"
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          compare-result: ${{ steps.compareresult.outputs.result }}
